# Generated by Django 5.1 on 2025-01-16 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0003_rename_confirmed_time_appointmentrequest_scheduled_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointmentrequest',
            name='department',
            field=models.CharField(choices=[('Diagnostic', 'Diagnostic'), ('Psychological', 'Psychological'), ('Orthopedics', 'Orthopedics'), ('General', 'General')], max_length=50),
        ),
    ]
