# Generated by Django 5.1 on 2025-01-11 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppointmentRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=15)),
                ('date', models.DateField()),
                ('department', models.CharField(choices=[('Diagnostic', 'Diagnostic'), ('Psychological', 'Psychological')], max_length=50)),
                ('doctor', models.CharField(choices=[('Diagnostic', 'Dr. Diagnostic'), ('Psychological', 'Dr. Psychological')], max_length=50)),
                ('message', models.TextField(blank=True, null=True)),
                ('confirmed', models.BooleanField(default=False)),
                ('confirmed_time', models.TimeField(blank=True, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='slot',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='user',
        ),
        migrations.DeleteModel(
            name='Doctor',
        ),
        migrations.RemoveField(
            model_name='healthtip',
            name='topic',
        ),
        migrations.DeleteModel(
            name='AppointmentSlot',
        ),
        migrations.DeleteModel(
            name='Appointment',
        ),
        migrations.DeleteModel(
            name='HealthTip',
        ),
        migrations.DeleteModel(
            name='HealthTopic',
        ),
    ]
