# Generated by Django 5.1 on 2025-01-19 09:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0006_report_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='report',
            options={'verbose_name': 'Report', 'verbose_name_plural': 'Reports'},
        ),
    ]
