# Generated by Django 5.1 on 2025-01-19 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0008_alter_report_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointmentrequest',
            name='payment_proof',
            field=models.ImageField(blank=True, null=True, upload_to='payment_proofs/'),
        ),
    ]
